"""Release notes generator for sprint completion."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path


def build_release_notes_md(
    cycle_name: str,
    features: list[dict],
    change_log: str,
    test_report: dict | None = None,
    git_tag: str | None = None,
) -> str:
    """Build structured markdown release notes.

    Args:
        cycle_name: Name of the Plane cycle/sprint.
        features: List of feature dicts with 'name', 'passes', 'category' keys.
        change_log: Git log output (oneline format).
        test_report: Optional test report dict with total_test_runs, overall_pass_rate,
                     and feature_summaries.
        git_tag: Optional git tag name.

    Returns:
        Markdown string.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    passing = sum(1 for f in features if f.get("passes"))
    total = len(features)

    lines: list[str] = []

    # Header
    lines.append(f"# Release Notes: {cycle_name}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Date:** {now}")
    if git_tag:
        lines.append(f"- **Tag:** `{git_tag}`")
    lines.append(f"- **Features:** {passing}/{total} passing")
    if test_report:
        rate = test_report.get("overall_pass_rate", 0)
        runs = test_report.get("total_test_runs", 0)
        lines.append(f"- **Test Runs:** {runs} ({rate:.0f}% pass rate)")
    lines.append("")

    # Features by category
    categories: dict[str, list[dict]] = {}
    for f in features:
        cat = f.get("category", "Uncategorized")
        categories.setdefault(cat, []).append(f)

    lines.append("## Features")
    lines.append("")
    for cat in sorted(categories.keys()):
        lines.append(f"### {cat}")
        lines.append("")
        for f in categories[cat]:
            status = "PASS" if f.get("passes") else "FAIL"
            lines.append(f"- [{status}] {f['name']}")
        lines.append("")

    # Test results table
    if test_report and test_report.get("feature_summaries"):
        lines.append("## Test Results")
        lines.append("")
        lines.append("| Feature | Runs | Pass | Fail | Rate | Last Result |")
        lines.append("|---------|------|------|------|------|-------------|")
        for s in test_report["feature_summaries"]:
            total_runs = s.get("total_runs", 0)
            pass_count = s.get("pass_count", 0)
            fail_count = s.get("fail_count", 0)
            rate = (pass_count / total_runs * 100) if total_runs > 0 else 0
            last = "PASS" if s.get("last_result") else "FAIL" if s.get("last_result") is not None else "-"
            lines.append(
                f"| {s.get('feature_name', '?')} | {total_runs} | {pass_count} | "
                f"{fail_count} | {rate:.0f}% | {last} |"
            )
        lines.append("")

    # Change log
    if change_log:
        lines.append("## Change Log")
        lines.append("")
        lines.append("```")
        lines.append(change_log)
        lines.append("```")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by MQ DevEngine at {now}*")
    lines.append("")

    return "\n".join(lines)


def save_release_notes(project_dir: Path, cycle_name: str, content: str) -> Path:
    """Save release notes to releases/ directory in the project.

    Args:
        project_dir: Project root directory.
        cycle_name: Cycle name (used for filename).
        content: Markdown content.

    Returns:
        Path to the saved file.
    """
    slug = re.sub(r"[^a-z0-9]+", "-", cycle_name.lower()).strip("-")
    releases_dir = project_dir / "releases"
    releases_dir.mkdir(parents=True, exist_ok=True)
    path = releases_dir / f"sprint-{slug}.md"
    path.write_text(content, encoding="utf-8")
    return path
